### ISSUE TITLE
requirements.txt problem

### ISSUE THREAD

**Issue by AceBreadman** [Michael-Beukman/HWFC#1]
When installing in the conda environment as per the instructions, there is this problem:

"ERROR: Could not find a version that satisfies the requirement sip==4.19.13 (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0, 5.4.0, 5.5.0, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.1.0, 6.1.1, 6.2.0, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 6.5.1, 6.6.0, 6.6.1, 6.6.2, 6.7.0, 6.7.1, 6.7.2, 6.7.3, 6.7.4, 6.7.5, 6.7.6, 6.7.7, 6.7.8, 6.7.9, 6.7.10, 6.7.11, 6.7.12, 6.8.0, 6.8.1, 6.8.2, 6.8.3)
ERROR: No matching distribution found for sip==4.19.13"

**Comment by Michael-Beukman** [comment]
Thanks for the issue @AceBreadman. It should be fixed now.

**Comment by AceBreadman** [comment]
Thanks!
